project:
  type: website

# Meta
description-meta: "Quarto Academic Website Template adapted by Dr. Gang He"
author-meta: "Patrick Neff, PD Dr."

website:
  title: "rea.lab"
  image: "https://quarto.org/quarto.png"
  description: "Website of rea.lab"
 
  navbar:
    background: light  # You can change the background color here

    left:   # You can comment out all navigation items here if you just like to keep the index page only
#      - text: Home
#        href: index.qmd
      - text: About
        menu:
          - text: News
            href: posts.qmd#category=news
          - text: Events
            href: posts.qmd#category=event      
          - text: Contact
            href: contact.qmd             
      - text: Research
        menu:
          - text: List of Publications
            href: publications.qmd
          - text: Projects
            href: projects.qmd
      - text: Labs
        href: labs.qmd
      - text: Outreach
        menu:
        - text: Presentations
          href: posts.qmd#category=presentation
      - text: Partners
        href: partners.qmd
      - text: Group   # Comment the Group part out to remove the Group page
        href: people.qmd

    right:
      - text: CV
        href: files/nsf-biosketch.pdf
      # - '<a href="https://github.com/drganghe/quarto-academic-website-template" target="_blank"><i class="fa-brands fa-github"></i> GitHub</a>'
      # - '<a href="https://bsky.app" target="_blank">Bluesky</a>'
      # - '<a href="posts.xml" target="_blank">RSS</a>'
  
  page-navigation: true
  
  page-footer: 
    left: "[Your Name](http://www.github.com) &copy; <script>document.write(new Date().getFullYear())</script>" 
    center: "Build on [Quart Academic Website Template](https://github.com/drganghe/quarto-academic-website-template) adapted by [Dr. Gang He](http://drganghe.github.io)"
    # right:
    #   - '<a href="https://github.com/drganghe/quarto-academic-website-template" target="_blank"><i class="fa-brands fa-github"></i> GitHub</a>'
    #   - '<a href="https://bsky.app" target="_blank">Bluesky</a>'
    #   - '<a href="posts.xml" target="_blank">RSS</a>'
  
  search:
    location: navbar
    type: textbox
  
  reader-mode: true

  draft-mode: unlinked
  
  repo-url: https://github.com/jaia137/realab
#  repo-actions: [edit, issue, source]
  
  open-graph: true
  
  twitter-card: true 
#  card-style: summary      
  
  site-url: "https://jaia137.github.io/realab/"
  
  google-analytics:
    tracking-id: ""  # Please delete or replace with your own tracking ID
    anonymize-ip: true 

bibliography: references.bib  # Add references.bib to the root folder to enable the bibliography function

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    footnotes-hover: true
    code-copy: true
    code-link: true
    code-overflow: wrap
    fig-align: center
    link-external-icon: false
    link-external-newwindow: true
    email-obfuscation: javascript
    link-external-filter: '^(?:http:|https:)\/\/drganghe\.github\.io\/custom'
    include-in-header: "files/includes/_academic.qmd"

